Ch en2ru
EgorBu/mathematics_dataset pull request #2
Opened 2024-07-30 18:40 UTC by CHern0g0r

2024-07-31 14:03 UTC, EgorBu requested changes
Отличная работа была проделана!
Предлагаю пару вещей улучшить перед merge
* удалить закомментированный код в нескольких местах
* добавить нескольким функциям докстринги в формате репозитория
* в паре мест добавить описание тех или иных магических аргументов, которые передаются в функцию в зависимости от контекста

2024-07-31 14:03 UTC, EgorBu commented on mathematics_dataset/util/display.py
> +_ord_cases_3 = {
нужно объяснение - почему 3?
Также нужно объяснение по структуре словаря

2024-07-31 14:03 UTC, EgorBu commented on mathematics_dataset/util/display.py
> +    root = _ORD_ROOTS[x]
нет проверки на то, что можем выйти за пределы первых 20 чисел - что тогда произойдет?

2024-07-31 14:03 UTC, EgorBu commented on mathematics_dataset/util/display.py
> +def _get_ord_cases(x, gen='male', case='nomn', is_sing=True):
давай добавлять докстринги в формате репозитория + typings для типов

2024-07-31 14:03 UTC, EgorBu commented on mathematics_dataset/util/display.py
> +def _get_numer(x):
```suggestion
def _convert_num_to_string(x):
```
или можно подумать над каким-то названием, которое более развернуто будет говорить про то. что делает функция

плюс докстринг и typing давай везде добавим

2024-07-31 14:03 UTC, EgorBu commented on mathematics_dataset/util/display.py
> +    words = [num2words(n, lang='ru')] if n > 0 else []
`num2words` не справляется адекватно? По логике она должна полностью число конвертировать - есть какие-то проблемы с этим?

2024-07-31 14:03 UTC, EgorBu commented on mathematics_dataset/util/display.py
> +    l0 = l%10
blackify

2024-07-31 14:03 UTC, EgorBu commented on mathematics_dataset/util/display.py
> +        # if denom <= 0 or denom >= len(_PLURAL_DENOMINATORS):
давай удалим все закомментированные участки кода

2024-07-31 14:03 UTC, EgorBu commented on mathematics_dataset/util/display.py
> +            denom_word = StringOrdinal(denom).str_by_form('femn', 'nomn')
давай добавим комментарий с обоснованием выбора аргументов - это неочевидно

2024-07-31 14:03 UTC, EgorBu commented on mathematics_dataset/util/display.py
> +        # if denom <= 0 or denom >= len(_PLURAL_DENOMINATORS):
здесь и в других местах

2024-07-31 14:03 UTC, EgorBu commented on mathematics_dataset/util/display.py
> +    def str_by_form(self, gen='male', case='nomn', is_sing=True):
`def _get_numer(x):` выглядит очень походе по логике - может стоит удалить `def _get_numer(x):`? или `def _get_numer(x):` переопределить как вызов этой функции с какими-то дефолтными значениями?

2024-07-31 14:03 UTC, EgorBu commented on mathematics_dataset/modules/calculus.py
> +
лишняя пустая линия

2024-07-31 14:03 UTC, EgorBu commented on mathematics_dataset/modules/comparison.py
> +    qt = random.choice([
хорошая идея про шаблонизацию такого вопроса)

2024-07-31 14:12 UTC, EgorBu commented on mathematics_dataset/modules/arithmetic.py
> +            description="Пусть {self} = {p} + {q}.",
рекомендую исключить этот файл из текущего PR - он будет пересекаться с другим PR, усложнит тебе процесс разработки немного

2024-08-01 10:49 UTC, CHern0g0r commented on mathematics_dataset/util/display.py
> +    words = [num2words(n, lang='ru')] if n > 0 else []
Проблемы с падежами, они из коробки не поддерживаются

2024-08-01 10:50 UTC, CHern0g0r commented on mathematics_dataset/util/display.py
> +    def str_by_form(self, gen='male', case='nomn', is_sing=True):
_get_numer = получить числитель дроби

2024-08-01 11:03 UTC, CHern0g0r commented on mathematics_dataset/util/display.py
> +    l0 = l%10
?

2024-08-01 11:11 UTC, CHern0g0r commented on mathematics_dataset/util/display.py
> +    def str_by_form(self, gen='male', case='nomn', is_sing=True):
Тут просто получаем ординал, поэтому разные функции

2024-08-01 11:41 UTC, CHern0g0r commented on mathematics_dataset/util/display.py
> +_ord_cases_3 = {
Добавил

2024-08-01 11:41 UTC, CHern0g0r commented on mathematics_dataset/util/display.py
> +    root = _ORD_ROOTS[x]
Добавил

2024-08-01 11:42 UTC, CHern0g0r commented on mathematics_dataset/util/display.py
> +def _get_ord_cases(x, gen='male', case='nomn', is_sing=True):
Done typings

2024-08-01 11:44 UTC, CHern0g0r commented on mathematics_dataset/util/display.py
> +def _get_numer(x):
Выдает строку для numer(al) - числителя.

2024-08-01 11:44 UTC, CHern0g0r commented on mathematics_dataset/util/display.py
> +        # if denom <= 0 or denom >= len(_PLURAL_DENOMINATORS):
Done

2024-08-01 11:45 UTC, CHern0g0r commented on mathematics_dataset/util/display.py
> +            denom_word = StringOrdinal(denom).str_by_form('femn', 'nomn')
Done

2024-08-01 11:45 UTC, CHern0g0r commented on mathematics_dataset/modules/calculus.py
> +
to much

2024-08-01 11:45 UTC, CHern0g0r commented on mathematics_dataset/modules/arithmetic.py
> +            description="Пусть {self} = {p} + {q}.",
Done

2024-08-01 14:39 UTC, EgorBu commented on mathematics_dataset/util/display.py
> +    l0 = l%10
имел в виду, что можно black применить, чтобы стиль автоматически применить - вроде должны быть пробелы вокруг знаков типа деления

2024-08-01 15:42 UTC, EgorBu requested changes
Отлично - почти можно мерджить - давай еще одну короткую итерацию сделаем по полировке и, думаю, смерджим

2024-08-01 15:42 UTC, EgorBu commented on mathematics_dataset/modules/measurement.py
> +    Unit("метр", "m"): 1,
давай сокращенные названия тоже на русском писать - это ведь сокращенное название вторым аргументом идет в Unit?

2024-08-01 15:42 UTC, EgorBu commented on mathematics_dataset/modules/measurement.py
> +    # templates = tempate x (target_number, target_case) x base_case
```suggestion
    # templates = [(template, (target_number, target_case), base_case), ...]
```

2024-08-01 15:42 UTC, EgorBu commented on mathematics_dataset/modules/measurement.py
> +def set_form(root: str, number: str, case: str):
докстринги с примерами очень помогут пониманию того, что эта и следующая функция делают

2024-08-01 15:42 UTC, EgorBu commented on mathematics_dataset/util/display.py
> +# Numbers with 3 in the end is exception in terms of cases.
```suggestion
# Numbers with 3 in the end is exception in terms of cases.
# `третИЙ` - _ord_cases_3[True]["nomn"]["male"]

2024-08-02 07:10 UTC, CHern0g0r commented
Я убрал знак '×' из arithmetic.py, потому что * - кондовый знак, который в остальных примерах используется.

2024-08-02 12:22 UTC, EgorBu approved these changes
Отличная работа! Спасибо!

2024-08-02 12:22 UTC, merged